@baseUrl = http://localhost:5088

### Index
GET {{baseUrl}}
    Content-Type: application/json


### Cadastro usuario
POST {{baseUrl}}/cadastrar
    Content-Type: application/json

{
    "nome": "teste",
    "senha": "teste",
    "email": "teste123414@gmail.com"
}

### Logar usuario
POST {{baseUrl}}/login 
    Content-Type: application/json

{
    "email": "teste123414@gmail.com",
    "senha": "teste"
}

### Cria um Board
POST {{baseUrl}}/api/boards
    Content-Type: application/json

{
  "name": "teste12312321",
  "usuarioId": 1,
  "isPublic": true
}

### Listar Boards (precisa do id do usuario)
GET {{baseUrl}}/api/boards/1

### Criar Card/tarefa
POST {{baseUrl}}/api/cards
    Content-Type: application/json

{
    "title": "teste",
    "description": "teste",
    "boardId": 1,
    "situacao": 1
}

### Deletar uma tarefa/card
DELETE {{baseUrl}}/api/cards/2
    Content-Type: application/json


### Deletar Board e seus cards
DELETE {{baseUrl}}/api/boards/7
    Content-Type: application/json


### Editar Board
PUT {{baseUrl}}/api/boards/1 
    Content-Type: application/json

{
    "name": "teste123124",
    "isPublic": true
}

### Editar Card/Tarefa
PUT {{baseUrl}}/api/cards/2 
    Content-Type: application/json

{
    "title": "teste123",
    "description": "teste123",
    "situacao": 2
}

### Consultar card/tarefa
GET {{baseUrl}}/api/boards/cards/1

### Visualizar boards publicos
GET {{baseUrl}}/api/boards/publicos