@baseUrl = http://localhost:5088

### Index
GET {{baseUrl}}
    Content-Type: application/json


### Cadastro usuario
POST {{baseUrl}}/cadastrar
    Content-Type: application/json

{
    "nome": "andre",
    "senha": "andre",
    "email": "andre@gmail.com"
}

### Logar usuario
POST {{baseUrl}}/login 
    Content-Type: application/json

{
    "email": "andre@gmail.com",
    "senha": "andre"
}

### Cria um Board
POST {{baseUrl}}/api/boards
    Content-Type: application/json

{
  "name": "Board1",
  "usuarioId": 3,
  "isPublic": false
}

### Consulta Boards (precisa do id do board)
GET {{baseUrl}}/api/boards/consultar/5
    Content-Type: application/json


### Listar Boards (precisa do id do usuario)
GET {{baseUrl}}/api/boards/1

### Criar Card/tarefa
POST {{baseUrl}}/api/cards
    Content-Type: application/json

{
    "title": "Tarefa1",
    "description": "Tarefa1 - Teste",
    "boardId": 5,
    "situacao": 1
}

### Pegar infos da tarefa
GET {{baseUrl}}/api/cards/13
    Content-Type: application/json


### Deletar uma tarefa/card
DELETE {{baseUrl}}/api/cards/2
    Content-Type: application/json


### Deletar Board e seus cards
DELETE {{baseUrl}}/api/boards/8
    Content-Type: application/json


### Editar Board
PUT {{baseUrl}}/api/boards/8
    Content-Type: application/json

{
    "name": "Board1",
    "isPublic": true
}

### Editar Card/Tarefa
PUT {{baseUrl}}/api/cards/2 
    Content-Type: application/json

{
    "title": "teste123",
    "description": "teste123",
    "situacao": 2
}

### Consultar card/tarefa
GET {{baseUrl}}/api/boards/cards/9

### Visualizar boards publicos
GET {{baseUrl}}/api/boards/publicos