@baseUrl = http://localhost:5088

### Index
GET {{baseUrl}}
    Content-Type: application/json


### Cadastro usuario
POST {{baseUrl}}/cadastrar
    Content-Type: application/json

{
    "nome": "teste",
    "senha": "teste",
    "email": "teste@gmail.com"
}

### Logar usuario
POST {{baseUrl}}/login 
    Content-Type: application/json

{
    "email": "teste@gmail.com",
    "senha": "teste"
}

### Cria um Board
POST {{baseUrl}}/api/boards
    Content-Type: application/json

{
  "name": "teste3",
  "usuarioId": 1
}

### Listar Boards (precisa do id do usuario)
GET {{baseUrl}}/api/boards/1
